services:
  app:
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir app
      --reload-exclude ".venv/*"
      --reload-exclude "__pycache__/*"
      --reload-exclude ".git/*"
      --reload-exclude "logs/*"
      --reload-exclude "data/*"
    ports:
      []
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini

  worker:
    volumes:
      - .:/app
    command: python -m app.workers.main

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: bot_template_ngrok
    env_file:
      - .env
    command: http nginx:80
    ports:
      - "4040:4040"
    depends_on:
      - nginx

  nginx:
    ports:
      - "8000:80"
